# USER ROUTE

## POST

### Create a new account -- OK
POST http://127.0.0.1:3000/api/account/ 
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "BobPassword",
    "username": "BobUsername" 
}

## GET

### Get a single user -- OK

GET http://127.0.0.1:3000/api/account/11 

### Update a single user -- OK

PATCH http://127.0.0.1:3000/api/account/11 
Content-Type: application/json

{
    "email": "updatedBob@gmail.com",
    "username": "UpdatedBobUsername" 
}

### Delete a single user X - delete_user not detected

DELETE http://127.0.0.1:3000/api/account/1

######

# DECK ROUTE

## GET

### Get all decks from a user -- OK

GET http://127.0.0.1:3000/api/account/1/decks

### Get a single deck from a user -- OK

GET http://127.0.0.1:3000/api/account/1/decks/1

## POST

### Create a new deck -- X - needs user_id being set correctly

POST http://127.0.0.1:3000/api/account/1/decks/
Content-Type: application/json

{
    "name": "A new deck",
    "description": "Some description for the new deck"
}

## PATCH

### Update a single deck -- OK

PATCH http://127.0.0.1:3000/api/account/1/decks/1
Content-Type: application/json

{
    "description": "Some updated description",
    "name": "Some updated name" 
}

## DELETE

### Delete a single deck X -- SQL function delete_deck not detected

DELETE http://127.0.0.1:3000/api/account/1/decks/1

######

# CARD ROUTE

## GET

### Get all cards from a deck -- OK
GET http://127.0.0.1:3000/api/account/1/decks/1/cards

### Get a single card from a deck -- OK

GET http://127.0.0.1:3000/api/account/1/decks/1/cards/1

## POST

### Create a new card -- X - needs deck_id being set correctly

POST http://127.0.0.1:3000/api/account/1/decks/1/cards
Content-Type: application/json

{
    "front": "What's a reply for this card's question?",
    "back": "Some reply",
    "difficulty": "1"
}

## PATCH

### Update a single card -- OK

PATCH http://127.0.0.1:3000/api/account/1/decks/1/cards/1
Content-Type: application/json

{
    "front": "What's a reply for this card's question?",
    "back": "Some reply",
    "deck_id": "1",
    "difficulty": "1"
}

## DELETE

### Delete a single card -- X - SQL function delete_card not detected

DELETE http://127.0.0.1:3000/api/account/1/decks/1/cards/1

######

# AUTH ROUTE

## POST

### Log into an existing account -- OK
POST http://127.0.0.1:3000/api/auth/ 
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "BobPassword"
}

### Try to log into a fake account -- OK
POST http://127.0.0.1:3000/api/auth/ 
Content-Type: application/json

{
    "email": "fakebob@gmail.com",
    "password": "FakeBobPassword"
}

